# Generated by Django 6.0.6 on 2026-06-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('remind_at', models.DateTimeField(help_text='Eslatma vaqti')),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=20)),
                ('title', models.CharField(help_text="Kun nomi, misol: Fizika o'rganish kuni", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('time', models.TimeField(help_text='Vazifa vaqti')),
                ('notified', models.BooleanField(default=False)),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.weekday')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
